// <auto-generated />
using CoffeeDelivery.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeDelivery.API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231217170335_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CoffeeDelivery.API.Models.Coffee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("coffee_id");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("HasAlcohol")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_alcohol");

                    b.Property<bool>("HasMilk")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_milk");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.Property<int>("Temperature")
                        .HasColumnType("INTEGER")
                        .HasColumnName("temperature");

                    b.HasKey("Id")
                        .HasName("coffee_id");

                    b.ToTable("coffees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            Description = "O tradicional café feito com água quente e grãos moídos",
                            HasAlcohol = false,
                            HasMilk = false,
                            Name = "Expresso Tradicional",
                            Price = 9.9000000000000004,
                            Temperature = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            Description = "Expresso diluído, menos intenso que o tradicional",
                            HasAlcohol = false,
                            HasMilk = false,
                            Name = "Expresso Americano",
                            Price = 9.9000000000000004,
                            Temperature = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            Description = "Café expresso tradicional com espuma cremosa",
                            HasAlcohol = false,
                            HasMilk = false,
                            Name = "Expresso Cremoso",
                            Price = 9.9000000000000004,
                            Temperature = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            Description = "Meio a meio expresso tradicional com leite vaporizado",
                            HasAlcohol = false,
                            HasMilk = true,
                            Name = "Café com Leite",
                            Price = 9.9000000000000004,
                            Temperature = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            Description = "Uma dose de café expresso com o dobro de leite e espuma cremosa",
                            HasAlcohol = false,
                            HasMilk = true,
                            Name = "Latte",
                            Price = 9.9000000000000004,
                            Temperature = 1
                        },
                        new
                        {
                            Id = 6,
                            Category = 1,
                            Description = "Bebida com canela feita de doses iguais de café, leite e espuma",
                            HasAlcohol = false,
                            HasMilk = true,
                            Name = "Capuccino",
                            Price = 9.9000000000000004,
                            Temperature = 1
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            Description = "Café expresso com calda de chocolate, pouco leite e espuma",
                            HasAlcohol = false,
                            HasMilk = true,
                            Name = "Mocaccino",
                            Price = 9.9000000000000004,
                            Temperature = 1
                        },
                        new
                        {
                            Id = 8,
                            Category = 2,
                            Description = "Bebida feita com chocolate dissolvido no leite quente e café",
                            HasAlcohol = false,
                            HasMilk = true,
                            Name = "Chocolate Quente",
                            Price = 9.9000000000000004,
                            Temperature = 1
                        },
                        new
                        {
                            Id = 9,
                            Category = 2,
                            Description = "Drink gelado de café expresso com rum, creme de leite e hortelã",
                            HasAlcohol = true,
                            HasMilk = false,
                            Name = "Cubano",
                            Price = 9.9000000000000004,
                            Temperature = 2
                        },
                        new
                        {
                            Id = 10,
                            Category = 2,
                            Description = "Bebida preparada com grãos de café árabe e especiarias",
                            HasAlcohol = false,
                            HasMilk = false,
                            Name = "Árabe",
                            Price = 9.9000000000000004,
                            Temperature = 1
                        },
                        new
                        {
                            Id = 11,
                            Category = 2,
                            Description = "Bebida a base de café, uísque irlandês, açúcar e chantilly",
                            HasAlcohol = true,
                            HasMilk = false,
                            Name = "Irlandês",
                            Price = 9.9000000000000004,
                            Temperature = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
